server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.105.165.247:3306/lambda?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ZhangKe123!
    driver-class-name: com.mysql.cj.jdbc.Driver
